// Code generated by MockGen. DO NOT EDIT.
// Source: internal/message_broker/message_broker.go
//
// Generated by this command:
//
//	mockgen -source=internal/message_broker/message_broker.go -destination=internal/mocks/message_broker_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageBroker is a mock of MessageBroker interface.
type MockMessageBroker struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBrokerMockRecorder
	isgomock struct{}
}

// MockMessageBrokerMockRecorder is the mock recorder for MockMessageBroker.
type MockMessageBrokerMockRecorder struct {
	mock *MockMessageBroker
}

// NewMockMessageBroker creates a new mock instance.
func NewMockMessageBroker(ctrl *gomock.Controller) *MockMessageBroker {
	mock := &MockMessageBroker{ctrl: ctrl}
	mock.recorder = &MockMessageBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageBroker) EXPECT() *MockMessageBrokerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessageBroker) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMessageBrokerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessageBroker)(nil).Close))
}

// PublishEmailJob mocks base method.
func (m *MockMessageBroker) PublishEmailJob(ctx context.Context, to, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEmailJob", ctx, to, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishEmailJob indicates an expected call of PublishEmailJob.
func (mr *MockMessageBrokerMockRecorder) PublishEmailJob(ctx, to, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEmailJob", reflect.TypeOf((*MockMessageBroker)(nil).PublishEmailJob), ctx, to, subject, body)
}

// PublishSlackJob mocks base method.
func (m *MockMessageBroker) PublishSlackJob(ctx context.Context, userEmail, deviceID, content string, feedbackID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSlackJob", ctx, userEmail, deviceID, content, feedbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSlackJob indicates an expected call of PublishSlackJob.
func (mr *MockMessageBrokerMockRecorder) PublishSlackJob(ctx, userEmail, deviceID, content, feedbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSlackJob", reflect.TypeOf((*MockMessageBroker)(nil).PublishSlackJob), ctx, userEmail, deviceID, content, feedbackID)
}
