package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"fmt"
	"log"
	"rizon-test-task/internal/app"
	"rizon-test-task/internal/graphql/generated"
	"rizon-test-task/internal/graphql/model"
)

// RequestEmailAuthLink is the resolver for the requestEmailAuthLink field.
func (r *mutationResolver) RequestEmailAuthLink(ctx context.Context, email string) (bool, error) {
	if err := r.App.GenerateEmailAuthLink(ctx, email); err != nil {
		return false, err
	}
	return true, nil
}

// LoginWithEmailAndSecret is the resolver for the loginWithEmailAndSecret field.
func (r *mutationResolver) LoginWithEmailAndSecret(ctx context.Context, email string, secret string) (string, error) {
	token, err := r.App.EmailAuth(ctx, email, secret)
	if err != nil {
		// Check for known sentinel errors - these are user-friendly and can be returned as-is
		if errors.Is(err, app.ErrEmailAuthNotFound) ||
			errors.Is(err, app.ErrEmailAuthInvalidSecret) {
			return "", err
		}

		// Log unexpected errors for debugging
		log.Printf("Error: failed to authenticate user with email %s: %v", email, err)
		return "", err
	}

	return token, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return r.App.Hello(ctx)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := r.App.GetCurrentUser(ctx)
	if err != nil {
		// Check for authentication errors
		if errors.Is(err, app.ErrUnauthorized) {
			return nil, err
		}
		// Log unexpected errors for debugging
		log.Printf("Error: failed to get current user: %v", err)
		return nil, err
	}

	// Convert models.User to GraphQL model.User
	return &model.User{
		ID:        fmt.Sprintf("%d", user.ID),
		Email:     user.Email,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
